### PR TITLE
Add PFAM DB parser

### PR DESCRIPTION
**Pull request by nicolanrizzo**
#70:
I have created functions to:
- Extract the translated coding regions of the genome from the genbank file (details below).
- Submit the translations to Pfam.

At the moment, we have to write the path of the file to parse and the output file is in the CSV format.

### CODE REVIEW

**Comment by mbonsma** [comment]
Wonderful, it works great! I think the hardcoded file path is just fine for now. At some point when we stitch everything together it might get changed. And CSV is also good. 

Just one thing - could there be an additional column in the CSV output with the translation number (i.e. 1, 2, etc.)? It would also be good, but not essential, if there was a column with the location of the translation (the [CDS start and endpoints](https://github.com/goyalsid/phageParser/blob/master/data/Genbank_example.txt#L124). Sorry to spring more requirements on you - seeing the output has made me think of it.

**Comment by nicolanrizzo** [comment]
Done.

I have one question: is it normal that translations n. 6, 7, 8, 9 return 

> We did not find any Pfam-A matches to your search sequence

message in Pfam sequence search?

**Comment by mbonsma** [comment]
Yes, that makes sense. To the best of my knowledge, the CDS annotation includes every possible sequence that could be a gene, and it's likely that some of them aren't actual genes or that the function of the protein hasn't yet been determined. For example, gene 6 in the list has ["hypothetical protein"](https://github.com/goyalsid/phageParser/blob/master/data/Genbank_example.txt#L350) listed as its product, so there's probably no entry in Pfam for it.

As an aside, we could have just extracted the NCBI-annotated product from the Genbank file, but my biologist friends tell me the annotations are unreliable and going directly to Pfam is better.

**Comment by mbonsma** [comment]
Fixes issue #70

**Pull request merged**
